#!/usr/bin/env bash
# Regenerate src/bindings.rs from the committed fdk-aac headers.
#
#   ./gen-bindings.sh            # rewrite src/bindings.rs
#   ./gen-bindings.sh --check    # fail if src/bindings.rs is not what the headers say
#
# Why generated and committed rather than generated at build time: bindgen needs libclang,
# and a `-sys` crate whose entire selling point is that a consumer needs no C or C++
# toolchain cannot then require an LLVM installation to build. Upstream `fdk-aac-sys` makes
# the same choice. What it does not do is *check* the committed file, so nothing there
# notices when the headers move and the bindings do not — which is what `--check` and the CI
# job that runs it are for.
#
# One file for every target, and that is sound rather than lucky: bindgen emits
# `::std::os::raw::c_int` and `c_char` as *aliases*, which each target resolves for itself,
# so the same source is correct on aarch64 (where c_char is unsigned) and on x86_64 (where
# it is signed).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../../fdk-aac.env
. ../../fdk-aac.env

# Pinned, because bindgen's output is not stable across its own versions — field ordering,
# the shape of the generated enum constants and the layout tests have all changed between
# releases. An unpinned generator turns `--check` into a test of which bindgen the runner
# happened to install.
BINDGEN_VERSION=0.72.1

out=src/bindings.rs

command -v bindgen >/dev/null 2>&1 || {
  echo "bindgen is not installed. cargo install bindgen-cli --version $BINDGEN_VERSION --locked" >&2
  exit 1
}
actual_version="$(bindgen --version | awk '{print $2}')"
[ "$actual_version" = "$BINDGEN_VERSION" ] || {
  echo "bindgen $actual_version is installed but this file is generated with $BINDGEN_VERSION" >&2
  echo "  cargo install bindgen-cli --version $BINDGEN_VERSION --locked --force" >&2
  exit 1
}

generate() {
  # Layout checks kept, deliberately — no `--no-layout-tests`. They are what makes
  # committing *one* bindings.rs for four targets an assertion rather than an assumption:
  # the sizes and alignments in them were computed by clang on the generating machine, and
  # every other target checks them against its own.
  #
  # bindgen 0.72 emits these as `const _: () = { ["Size of X"][size_of::<X>() - N]; }`,
  # which fails at **compile** time rather than as a `#[test]` — better than a test, since
  # a consumer who never runs the test suite still cannot build against a struct that packs
  # differently on their target. The odd indexing is how a const assertion produces a
  # readable message: the index is out of bounds unless the difference is zero, and the
  # string is what the compiler prints.
  bindgen wrapper.h \
    --allowlist-file '.*/fdk-aac/.*' \
    --default-enum-style consts \
    --no-doc-comments \
    --raw-line "// @generated by gen-bindings.sh from the fdk-aac $FDK_AAC_VERSION headers in" \
    --raw-line "// include/fdk-aac/ — do not edit. Regenerate with bindgen $BINDGEN_VERSION." \
    --raw-line "//" \
    --raw-line "// \`--allowlist-file\` restricts this to items declared by fdk-aac's own headers." \
    --raw-line "// Without it the output also carries whatever <stddef.h> and <sys/types.h> declare" \
    --raw-line "// on the generating machine, which is glibc's idea of them — portable in practice" \
    --raw-line "// because they are bare aliases, but not something to ship on that reasoning." \
    --raw-line "#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]" \
    --raw-line "// clippy::approx_constant: fdk-aac's machine_type.h defines M_PI, and a" \
    --raw-line "// generated transcription of somebody else's header is not the place to" \
    --raw-line "// substitute std::f64::consts::PI for the value they wrote." \
    --raw-line "#![allow(clippy::approx_constant)]" \
    -- -I include
}

if [ "${1:-}" = "--check" ]; then
  # Compared as text rather than by regenerating in place and asking git: this has to work
  # in a CI job that has not necessarily checked out with a clean tree, and the diff is
  # worth printing either way.
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  generate > "$tmp"
  if diff -u "$out" "$tmp"; then
    echo "$out matches the committed fdk-aac $FDK_AAC_VERSION headers"
    exit 0
  fi
  echo "$out is stale — run gen-bindings.sh" >&2
  exit 1
fi

generate > "$out"
echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines from fdk-aac $FDK_AAC_VERSION)"
