#!/usr/bin/env bash
# Regenerate src/version.rs from the pinned fdk-aac sources.
#
#   ./gen-version.sh            # rewrite src/version.rs
#   ./gen-version.sh --check    # fail if src/version.rs is not what the sources say
#
# This file exists because of something fdk-aac does not have. libopus exposes
# `opus_get_version_string()`, so a test can ask the linked library which version it is and
# fail if the answer is not the pinned one — the single most useful assertion a repository
# like this one can make, because it catches a stale cache, a stray system library winning
# the link, and a release that shipped the wrong archive.
#
# fdk-aac exposes no such thing. Its package version (2.0.3) is a number in CMakeLists.txt
# that never reaches a compiler. What `aacEncGetLibInfo` reports is the *module* version of
# the encoder and decoder libraries — 4.0.1 and 3.2.0 here — which are #defines in the .cpp
# files and do move between releases.
#
# So the substitute: lift those numbers out of the pinned source at generation time, commit
# them, and have the tests and the e2e binary require the linked archive to report exactly
# these. Different pinned version, different constants, failing test — which is the property
# that was wanted.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../../fdk-aac.env
. ../../fdk-aac.env

out=src/version.rs
src="../../build/fdk-aac-${FDK_AAC_VERSION}"

[ -d "$src" ] || {
  echo "no unpacked source at $src — run ../../sync-prebuilt.sh --headers, which fetches it" >&2
  exit 1
}

# One `#define <name> <integer>` out of one file, and nothing else accepted: an empty result
# would otherwise become an empty string in the generated file and a constant of `` that
# fails to compile with an error naming the wrong problem.
define_of() {
  local file="$1" name="$2" value
  value="$(awk -v n="$name" '$1 == "#define" && $2 == n && $3 ~ /^[0-9]+$/ { print $3; exit }' "$file")"
  [ -n "$value" ] || {
    echo "no '#define $name <integer>' in $file — has upstream renamed it?" >&2
    return 1
  }
  printf '%s' "$value"
}

enc_src="$src/libAACenc/src/aacenc_lib.cpp"
dec_src="$src/libAACdec/src/aacdecoder_lib.cpp"

enc0="$(define_of "$enc_src" AACENCODER_LIB_VL0)"
enc1="$(define_of "$enc_src" AACENCODER_LIB_VL1)"
enc2="$(define_of "$enc_src" AACENCODER_LIB_VL2)"
dec0="$(define_of "$dec_src" AACDECODER_LIB_VL0)"
dec1="$(define_of "$dec_src" AACDECODER_LIB_VL1)"
dec2="$(define_of "$dec_src" AACDECODER_LIB_VL2)"

generated="$(
  cat <<EOF
//! @generated by gen-version.sh from the fdk-aac $FDK_AAC_VERSION sources — do not edit.
//!
//! fdk-aac reports no package version at runtime. These are the encoder and decoder
//! *module* versions, lifted from libAACenc/src/aacenc_lib.cpp and
//! libAACdec/src/aacdecoder_lib.cpp, and they are what \`aacEncGetLibInfo\` and
//! \`aacDecoder_GetLibInfo\` fill in. Asserting the linked archive reports these is this
//! crate's stand-in for \`opus_get_version_string()\`.

/// The fdk-aac release these bindings and the published archives were built from.
pub const FDK_AAC_VERSION: &str = "$FDK_AAC_VERSION";

/// \`aacEncGetLibInfo\` must report this for the "AAC Encoder" module.
pub const ENCODER_LIB_VERSION: (u32, u32, u32) = ($enc0, $enc1, $enc2);

/// \`aacDecoder_GetLibInfo\` must report this for the "AAC Decoder Lib" module.
pub const DECODER_LIB_VERSION: (u32, u32, u32) = ($dec0, $dec1, $dec2);

/// The packing \`LIB_VERSION\` uses, from libSYS/include/FDK_audio.h:703:
///
/// \`\`\`text
/// (lev0 << 24 & 0xff000000) | (lev1 << 16 & 0x00ff0000) | (lev2 << 8 & 0x0000ff00)
/// \`\`\`
///
/// Note the low byte is unused — \`LIB_VERSION(4, 0, 1)\` is \`0x04000100\`, not
/// \`0x00040001\`. Open-coding this shift at each call site is how one of them ends up
/// with the natural-looking packing and compares two numbers that are never equal.
pub const fn packed(version: (u32, u32, u32)) -> u32 {
    (version.0 << 24) | (version.1 << 16) | (version.2 << 8)
}
EOF
)"

if [ "${1:-}" = "--check" ]; then
  if printf '%s\n' "$generated" | diff -u "$out" -; then
    echo "$out matches the fdk-aac $FDK_AAC_VERSION sources"
    exit 0
  fi
  echo "$out is stale — run gen-version.sh" >&2
  exit 1
fi

printf '%s\n' "$generated" > "$out"
echo "wrote $out (encoder $enc0.$enc1.$enc2, decoder $dec0.$dec1.$dec2)"
