/* automatically generated by rust-bindgen 0.72.1 */

// @generated by gen-bindings.sh from the fdk-aac 2.0.3 headers in
// include/fdk-aac/ — do not edit. Regenerate with bindgen 0.72.1.
//
// `--allowlist-file` restricts this to items declared by fdk-aac's own headers.
// Without it the output also carries whatever <stddef.h> and <sys/types.h> declare
// on the generating machine, which is glibc's idea of them — portable in practice
// because they are bare aliases, but not something to ship on that reasoning.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
// clippy::approx_constant: fdk-aac's machine_type.h defines M_PI, and a
// generated transcription of somebody else's header is not the place to
// substitute std::f64::consts::PI for the value they wrote.
#![allow(clippy::approx_constant)]

pub const SHORT_BITS: u32 = 16;
pub const CHAR_BITS: u32 = 8;
pub const WAV_BITS: u32 = 16;
pub const SAMPLE_BITS: u32 = 16;
pub const ALIGNMENT_DEFAULT: u32 = 8;
pub const ALIGNMENT_EXTRES: u32 = 8;
pub const M_PI: f64 = 3.141592653589793;
pub const FDK_EXITCODE_OK: u32 = 0;
pub const FDK_EXITCODE_USAGE: u32 = 64;
pub const FDK_EXITCODE_DATAERROR: u32 = 65;
pub const FDK_EXITCODE_NOINPUT: u32 = 66;
pub const FDK_EXITCODE_UNAVAILABLE: u32 = 69;
pub const FDK_EXITCODE_SOFTWARE: u32 = 70;
pub const FDK_EXITCODE_CANTCREATE: u32 = 73;
pub const FDK_EXITCODE_IOERROR: u32 = 74;
pub const FDK_MAX_OVERLAYS: u32 = 8;
pub const AC_ER_VCB11: u32 = 1;
pub const AC_ER_RVLC: u32 = 2;
pub const AC_ER_HCR: u32 = 4;
pub const AC_SCALABLE: u32 = 8;
pub const AC_ELD: u32 = 16;
pub const AC_LD: u32 = 32;
pub const AC_ER: u32 = 64;
pub const AC_BSAC: u32 = 128;
pub const AC_USAC: u32 = 256;
pub const AC_RSV603DA: u32 = 512;
pub const AC_HDAAC: u32 = 1024;
pub const AC_RSVD50: u32 = 16384;
pub const AC_SBR_PRESENT: u32 = 32768;
pub const AC_SBRCRC: u32 = 65536;
pub const AC_PS_PRESENT: u32 = 131072;
pub const AC_MPS_PRESENT: u32 = 262144;
pub const AC_DRM: u32 = 524288;
pub const AC_INDEP: u32 = 1048576;
pub const AC_MPEGD_RES: u32 = 2097152;
pub const AC_SAOC_PRESENT: u32 = 4194304;
pub const AC_DAB: u32 = 8388608;
pub const AC_ELD_DOWNSCALE: u32 = 16777216;
pub const AC_LD_MPS: u32 = 33554432;
pub const AC_DRC_PRESENT: u32 = 67108864;
pub const AC_USAC_SCFGI3: u32 = 134217728;
pub const AC_CM_DET_CFG_CHANGE: u32 = 1;
pub const AC_CM_ALLOC_MEM: u32 = 2;
pub const AC_EL_USAC_TW: u32 = 1;
pub const AC_EL_USAC_NOISE: u32 = 2;
pub const AC_EL_USAC_ITES: u32 = 4;
pub const AC_EL_USAC_PVC: u32 = 8;
pub const AC_EL_USAC_MPS212: u32 = 16;
pub const AC_EL_USAC_LFE: u32 = 32;
pub const AC_EL_USAC_CP_POSSIBLE: u32 = 64;
pub const AC_EL_ENHANCED_NOISE: u32 = 128;
pub const AC_EL_IGF_AFTER_TNS: u32 = 256;
pub const AC_EL_IGF_INDEP_TILING: u32 = 512;
pub const AC_EL_IGF_USE_ENF: u32 = 1024;
pub const AC_EL_FULLBANDLPD: u32 = 2048;
pub const AC_EL_LPDSTEREOIDX: u32 = 4096;
pub const AC_EL_LFE: u32 = 8192;
pub const CC_MPEG_ID: u32 = 1048576;
pub const CC_IS_BASELAYER: u32 = 2097152;
pub const CC_PROTECTION: u32 = 4194304;
pub const CC_SBR: u32 = 8388608;
pub const CC_SBRCRC: u32 = 65536;
pub const CC_SAC: u32 = 131072;
pub const CC_RVLC: u32 = 16777216;
pub const CC_VCB11: u32 = 33554432;
pub const CC_HCR: u32 = 67108864;
pub const CC_PSEUDO_SURROUND: u32 = 134217728;
pub const CC_USAC_NOISE: u32 = 268435456;
pub const CC_USAC_TW: u32 = 536870912;
pub const CC_USAC_HBE: u32 = 1073741824;
pub const USAC_ID_BIT: u32 = 16;
pub const EXT_ID_BITS: u32 = 4;
pub const CAPF_AAC_LC: u32 = 1;
pub const CAPF_ER_AAC_LD: u32 = 2;
pub const CAPF_ER_AAC_SCAL: u32 = 4;
pub const CAPF_ER_AAC_LC: u32 = 8;
pub const CAPF_AAC_480: u32 = 16;
pub const CAPF_AAC_512: u32 = 32;
pub const CAPF_AAC_960: u32 = 64;
pub const CAPF_AAC_1024: u32 = 128;
pub const CAPF_AAC_HCR: u32 = 256;
pub const CAPF_AAC_VCB11: u32 = 512;
pub const CAPF_AAC_RVLC: u32 = 1024;
pub const CAPF_AAC_MPEG4: u32 = 2048;
pub const CAPF_AAC_DRC: u32 = 4096;
pub const CAPF_AAC_CONCEALMENT: u32 = 8192;
pub const CAPF_AAC_DRM_BSFORMAT: u32 = 16384;
pub const CAPF_ER_AAC_ELD: u32 = 32768;
pub const CAPF_ER_AAC_BSAC: u32 = 65536;
pub const CAPF_AAC_ELD_DOWNSCALE: u32 = 262144;
pub const CAPF_AAC_USAC_LP: u32 = 1048576;
pub const CAPF_AAC_USAC: u32 = 2097152;
pub const CAPF_ER_AAC_ELDV2: u32 = 8388608;
pub const CAPF_AAC_UNIDRC: u32 = 16777216;
pub const CAPF_ADTS: u32 = 1;
pub const CAPF_ADIF: u32 = 2;
pub const CAPF_LATM: u32 = 4;
pub const CAPF_LOAS: u32 = 8;
pub const CAPF_RAWPACKETS: u32 = 16;
pub const CAPF_DRM: u32 = 32;
pub const CAPF_RSVD50: u32 = 64;
pub const CAPF_SBR_LP: u32 = 1;
pub const CAPF_SBR_HQ: u32 = 2;
pub const CAPF_SBR_DRM_BS: u32 = 4;
pub const CAPF_SBR_CONCEALMENT: u32 = 8;
pub const CAPF_SBR_DRC: u32 = 16;
pub const CAPF_SBR_PS_MPEG: u32 = 32;
pub const CAPF_SBR_PS_DRM: u32 = 64;
pub const CAPF_SBR_ELD_DOWNSCALE: u32 = 128;
pub const CAPF_SBR_HBEHQ: u32 = 256;
pub const CAPF_DMX_BLIND: u32 = 1;
pub const CAPF_DMX_PCE: u32 = 2;
pub const CAPF_DMX_ARIB: u32 = 4;
pub const CAPF_DMX_DVB: u32 = 8;
pub const CAPF_DMX_CH_EXP: u32 = 16;
pub const CAPF_DMX_6_CH: u32 = 32;
pub const CAPF_DMX_8_CH: u32 = 64;
pub const CAPF_DMX_24_CH: u32 = 128;
pub const CAPF_LIMITER: u32 = 8192;
pub const CAPF_MPS_STD: u32 = 1;
pub const CAPF_MPS_LD: u32 = 2;
pub const CAPF_MPS_USAC: u32 = 4;
pub const CAPF_MPS_HQ: u32 = 16;
pub const CAPF_MPS_LP: u32 = 32;
pub const CAPF_MPS_BLIND: u32 = 64;
pub const CAPF_MPS_BINAURAL: u32 = 128;
pub const CAPF_MPS_2CH_OUT: u32 = 256;
pub const CAPF_MPS_6CH_OUT: u32 = 512;
pub const CAPF_MPS_8CH_OUT: u32 = 1024;
pub const CAPF_MPS_1CH_IN: u32 = 4096;
pub const CAPF_MPS_2CH_IN: u32 = 8192;
pub const CAPF_MPS_6CH_IN: u32 = 16384;
pub const AACENCODER_LIB_VL0: u32 = 4;
pub const AACENCODER_LIB_VL1: u32 = 0;
pub const AACENCODER_LIB_VL2: u32 = 1;
pub const AACDECODER_LIB_VL0: u32 = 3;
pub const AACDECODER_LIB_VL1: u32 = 2;
pub const AACDECODER_LIB_VL2: u32 = 0;
pub const AACDEC_CONCEAL: u32 = 1;
pub const AACDEC_FLUSH: u32 = 2;
pub const AACDEC_INTR: u32 = 4;
pub const AACDEC_CLRHIST: u32 = 8;
pub type INT = ::std::os::raw::c_int;
pub type UINT = ::std::os::raw::c_uint;
pub type SHORT = ::std::os::raw::c_short;
pub type USHORT = ::std::os::raw::c_ushort;
pub type SCHAR = ::std::os::raw::c_schar;
pub type UCHAR = ::std::os::raw::c_uchar;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type INT_PCM = SHORT;
pub const MEMORY_SECTION_SECT_DATA_L1: MEMORY_SECTION = 8192;
pub const MEMORY_SECTION_SECT_DATA_L2: MEMORY_SECTION = 8193;
pub const MEMORY_SECTION_SECT_DATA_L1_A: MEMORY_SECTION = 8194;
pub const MEMORY_SECTION_SECT_DATA_L1_B: MEMORY_SECTION = 8195;
pub const MEMORY_SECTION_SECT_CONSTDATA_L1: MEMORY_SECTION = 8196;
pub const MEMORY_SECTION_SECT_DATA_EXTERN: MEMORY_SECTION = 16384;
pub const MEMORY_SECTION_SECT_CONSTDATA_EXTERN: MEMORY_SECTION = 16385;
pub type MEMORY_SECTION = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn FDKprintf(szFmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn FDKprintfErr(szFmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn FDKgetchar() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FDKfprintf(
        stream: *mut ::std::os::raw::c_void,
        format: *const ::std::os::raw::c_char,
        ...
    ) -> INT;
}
unsafe extern "C" {
    pub fn FDKsprintf(
        str_: *mut ::std::os::raw::c_char,
        format: *const ::std::os::raw::c_char,
        ...
    ) -> INT;
}
unsafe extern "C" {
    pub fn FDKstrchr(s: *mut ::std::os::raw::c_char, c: INT) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FDKstrstr(
        haystack: *const ::std::os::raw::c_char,
        needle: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FDKstrcpy(
        dest: *mut ::std::os::raw::c_char,
        src: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FDKstrncpy(
        dest: *mut ::std::os::raw::c_char,
        src: *const ::std::os::raw::c_char,
        n: UINT,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FDKcalloc(n: UINT, size: UINT) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn FDKmalloc(size: UINT) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn FDKfree(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn FDKaalloc(size: UINT, alignment: UINT) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn FDKafree(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn FDKcalloc_L(n: UINT, size: UINT, s: MEMORY_SECTION) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn FDKaalloc_L(
        size: UINT,
        alignment: UINT,
        s: MEMORY_SECTION,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn FDKfree_L(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn FDKafree_L(ptr: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn FDKmemcpy(
        dst: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_void,
        size: UINT,
    );
}
unsafe extern "C" {
    pub fn FDKmemmove(
        dst: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_void,
        size: UINT,
    );
}
unsafe extern "C" {
    pub fn FDKmemclear(memPtr: *mut ::std::os::raw::c_void, size: UINT);
}
unsafe extern "C" {
    pub fn FDKmemset(memPtr: *mut ::std::os::raw::c_void, value: INT, size: UINT);
}
unsafe extern "C" {
    pub fn FDKmemcmp(
        s1: *const ::std::os::raw::c_void,
        s2: *const ::std::os::raw::c_void,
        size: UINT,
    ) -> INT;
}
unsafe extern "C" {
    pub fn FDKstrcmp(s1: *const ::std::os::raw::c_char, s2: *const ::std::os::raw::c_char) -> INT;
}
unsafe extern "C" {
    pub fn FDKstrncmp(
        s1: *const ::std::os::raw::c_char,
        s2: *const ::std::os::raw::c_char,
        size: UINT,
    ) -> INT;
}
unsafe extern "C" {
    pub fn FDKstrlen(s: *const ::std::os::raw::c_char) -> UINT;
}
unsafe extern "C" {
    pub fn IS_LITTLE_ENDIAN() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn TO_LITTLE_ENDIAN(val: UINT) -> UINT;
}
pub type FDKFILE = ::std::os::raw::c_void;
unsafe extern "C" {
    pub static FDKSEEK_SET: INT;
}
unsafe extern "C" {
    pub static FDKSEEK_CUR: INT;
}
unsafe extern "C" {
    pub static FDKSEEK_END: INT;
}
unsafe extern "C" {
    pub fn FDKfopen(
        filename: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut FDKFILE;
}
unsafe extern "C" {
    pub fn FDKfclose(FP: *mut FDKFILE) -> INT;
}
unsafe extern "C" {
    pub fn FDKfseek(FP: *mut FDKFILE, OFFSET: INT, WHENCE: ::std::os::raw::c_int) -> INT;
}
unsafe extern "C" {
    pub fn FDKftell(FP: *mut FDKFILE) -> INT;
}
unsafe extern "C" {
    pub fn FDKfflush(fp: *mut FDKFILE) -> INT;
}
unsafe extern "C" {
    pub fn FDKfwrite(
        ptrf: *const ::std::os::raw::c_void,
        size: INT,
        nmemb: UINT,
        fp: *mut FDKFILE,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn FDKfread(
        dst: *mut ::std::os::raw::c_void,
        size: INT,
        nmemb: UINT,
        fp: *mut FDKFILE,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn FDKfgets(
        dst: *mut ::std::os::raw::c_void,
        size: INT,
        fp: *mut FDKFILE,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn FDKrewind(fp: *mut FDKFILE);
}
unsafe extern "C" {
    pub fn FDKfeof(fp: *mut FDKFILE) -> INT;
}
unsafe extern "C" {
    pub fn FDKfwrite_EL(
        ptrf: *const ::std::os::raw::c_void,
        size: INT,
        nmemb: UINT,
        fp: *mut FDKFILE,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn FDKfread_EL(
        dst: *mut ::std::os::raw::c_void,
        size: INT,
        nmemb: UINT,
        fp: *mut FDKFILE,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn FDKprintDisclaimer();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CHANNEL_MAP_INFO {
    pub pChannelMap: *const UCHAR,
    pub numChannels: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CHANNEL_MAP_INFO"][::std::mem::size_of::<CHANNEL_MAP_INFO>() - 16usize];
    ["Alignment of CHANNEL_MAP_INFO"][::std::mem::align_of::<CHANNEL_MAP_INFO>() - 8usize];
    ["Offset of field: CHANNEL_MAP_INFO::pChannelMap"]
        [::std::mem::offset_of!(CHANNEL_MAP_INFO, pChannelMap) - 0usize];
    ["Offset of field: CHANNEL_MAP_INFO::numChannels"]
        [::std::mem::offset_of!(CHANNEL_MAP_INFO, numChannels) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FDK_channelMapDescr {
    pub pMapInfoTab: *const CHANNEL_MAP_INFO,
    pub mapInfoTabLen: UINT,
    pub fPassThrough: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FDK_channelMapDescr"][::std::mem::size_of::<FDK_channelMapDescr>() - 16usize];
    ["Alignment of FDK_channelMapDescr"][::std::mem::align_of::<FDK_channelMapDescr>() - 8usize];
    ["Offset of field: FDK_channelMapDescr::pMapInfoTab"]
        [::std::mem::offset_of!(FDK_channelMapDescr, pMapInfoTab) - 0usize];
    ["Offset of field: FDK_channelMapDescr::mapInfoTabLen"]
        [::std::mem::offset_of!(FDK_channelMapDescr, mapInfoTabLen) - 8usize];
    ["Offset of field: FDK_channelMapDescr::fPassThrough"]
        [::std::mem::offset_of!(FDK_channelMapDescr, fPassThrough) - 12usize];
};
unsafe extern "C" {
    pub fn FDK_chMapDescr_init(
        pMapDescr: *mut FDK_channelMapDescr,
        pMapInfoTab: *const CHANNEL_MAP_INFO,
        mapInfoTabLen: UINT,
        fPassThrough: UINT,
    );
}
unsafe extern "C" {
    pub fn FDK_chMapDescr_setPassThrough(
        pMapDescr: *mut FDK_channelMapDescr,
        fPassThrough: UINT,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn FDK_chMapDescr_getMapValue(
        pMapDescr: *const FDK_channelMapDescr,
        chIdx: UCHAR,
        mapIdx: UINT,
    ) -> UCHAR;
}
unsafe extern "C" {
    pub fn FDK_chMapDescr_isValid(pMapDescr: *const FDK_channelMapDescr) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static FDK_mapInfoTabWg4: [CHANNEL_MAP_INFO; 0usize];
}
unsafe extern "C" {
    pub static FDK_mapInfoTabLenWg4: UINT;
}
pub const FILE_FORMAT_FF_UNKNOWN: FILE_FORMAT = -1;
pub const FILE_FORMAT_FF_RAW: FILE_FORMAT = 0;
pub const FILE_FORMAT_FF_MP4_3GPP: FILE_FORMAT = 3;
pub const FILE_FORMAT_FF_MP4_MP4F: FILE_FORMAT = 4;
pub const FILE_FORMAT_FF_RAWPACKETS: FILE_FORMAT = 5;
pub type FILE_FORMAT = ::std::os::raw::c_int;
pub const TRANSPORT_TYPE_TT_UNKNOWN: TRANSPORT_TYPE = -1;
pub const TRANSPORT_TYPE_TT_MP4_RAW: TRANSPORT_TYPE = 0;
pub const TRANSPORT_TYPE_TT_MP4_ADIF: TRANSPORT_TYPE = 1;
pub const TRANSPORT_TYPE_TT_MP4_ADTS: TRANSPORT_TYPE = 2;
pub const TRANSPORT_TYPE_TT_MP4_LATM_MCP1: TRANSPORT_TYPE = 6;
pub const TRANSPORT_TYPE_TT_MP4_LATM_MCP0: TRANSPORT_TYPE = 7;
pub const TRANSPORT_TYPE_TT_MP4_LOAS: TRANSPORT_TYPE = 10;
pub const TRANSPORT_TYPE_TT_DRM: TRANSPORT_TYPE = 12;
pub type TRANSPORT_TYPE = ::std::os::raw::c_int;
pub const AUDIO_OBJECT_TYPE_AOT_NONE: AUDIO_OBJECT_TYPE = -1;
pub const AUDIO_OBJECT_TYPE_AOT_NULL_OBJECT: AUDIO_OBJECT_TYPE = 0;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_MAIN: AUDIO_OBJECT_TYPE = 1;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_LC: AUDIO_OBJECT_TYPE = 2;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_SSR: AUDIO_OBJECT_TYPE = 3;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_LTP: AUDIO_OBJECT_TYPE = 4;
pub const AUDIO_OBJECT_TYPE_AOT_SBR: AUDIO_OBJECT_TYPE = 5;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_SCAL: AUDIO_OBJECT_TYPE = 6;
pub const AUDIO_OBJECT_TYPE_AOT_TWIN_VQ: AUDIO_OBJECT_TYPE = 7;
pub const AUDIO_OBJECT_TYPE_AOT_CELP: AUDIO_OBJECT_TYPE = 8;
pub const AUDIO_OBJECT_TYPE_AOT_HVXC: AUDIO_OBJECT_TYPE = 9;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_10: AUDIO_OBJECT_TYPE = 10;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_11: AUDIO_OBJECT_TYPE = 11;
pub const AUDIO_OBJECT_TYPE_AOT_TTSI: AUDIO_OBJECT_TYPE = 12;
pub const AUDIO_OBJECT_TYPE_AOT_MAIN_SYNTH: AUDIO_OBJECT_TYPE = 13;
pub const AUDIO_OBJECT_TYPE_AOT_WAV_TAB_SYNTH: AUDIO_OBJECT_TYPE = 14;
pub const AUDIO_OBJECT_TYPE_AOT_GEN_MIDI: AUDIO_OBJECT_TYPE = 15;
pub const AUDIO_OBJECT_TYPE_AOT_ALG_SYNTH_AUD_FX: AUDIO_OBJECT_TYPE = 16;
pub const AUDIO_OBJECT_TYPE_AOT_ER_AAC_LC: AUDIO_OBJECT_TYPE = 17;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_18: AUDIO_OBJECT_TYPE = 18;
pub const AUDIO_OBJECT_TYPE_AOT_ER_AAC_LTP: AUDIO_OBJECT_TYPE = 19;
pub const AUDIO_OBJECT_TYPE_AOT_ER_AAC_SCAL: AUDIO_OBJECT_TYPE = 20;
pub const AUDIO_OBJECT_TYPE_AOT_ER_TWIN_VQ: AUDIO_OBJECT_TYPE = 21;
pub const AUDIO_OBJECT_TYPE_AOT_ER_BSAC: AUDIO_OBJECT_TYPE = 22;
pub const AUDIO_OBJECT_TYPE_AOT_ER_AAC_LD: AUDIO_OBJECT_TYPE = 23;
pub const AUDIO_OBJECT_TYPE_AOT_ER_CELP: AUDIO_OBJECT_TYPE = 24;
pub const AUDIO_OBJECT_TYPE_AOT_ER_HVXC: AUDIO_OBJECT_TYPE = 25;
pub const AUDIO_OBJECT_TYPE_AOT_ER_HILN: AUDIO_OBJECT_TYPE = 26;
pub const AUDIO_OBJECT_TYPE_AOT_ER_PARA: AUDIO_OBJECT_TYPE = 27;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_28: AUDIO_OBJECT_TYPE = 28;
pub const AUDIO_OBJECT_TYPE_AOT_PS: AUDIO_OBJECT_TYPE = 29;
pub const AUDIO_OBJECT_TYPE_AOT_MPEGS: AUDIO_OBJECT_TYPE = 30;
pub const AUDIO_OBJECT_TYPE_AOT_ESCAPE: AUDIO_OBJECT_TYPE = 31;
pub const AUDIO_OBJECT_TYPE_AOT_MP3ONMP4_L1: AUDIO_OBJECT_TYPE = 32;
pub const AUDIO_OBJECT_TYPE_AOT_MP3ONMP4_L2: AUDIO_OBJECT_TYPE = 33;
pub const AUDIO_OBJECT_TYPE_AOT_MP3ONMP4_L3: AUDIO_OBJECT_TYPE = 34;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_35: AUDIO_OBJECT_TYPE = 35;
pub const AUDIO_OBJECT_TYPE_AOT_RSVD_36: AUDIO_OBJECT_TYPE = 36;
pub const AUDIO_OBJECT_TYPE_AOT_AAC_SLS: AUDIO_OBJECT_TYPE = 37;
pub const AUDIO_OBJECT_TYPE_AOT_SLS: AUDIO_OBJECT_TYPE = 38;
pub const AUDIO_OBJECT_TYPE_AOT_ER_AAC_ELD: AUDIO_OBJECT_TYPE = 39;
pub const AUDIO_OBJECT_TYPE_AOT_USAC: AUDIO_OBJECT_TYPE = 42;
pub const AUDIO_OBJECT_TYPE_AOT_SAOC: AUDIO_OBJECT_TYPE = 43;
pub const AUDIO_OBJECT_TYPE_AOT_LD_MPEGS: AUDIO_OBJECT_TYPE = 44;
pub const AUDIO_OBJECT_TYPE_AOT_MP2_AAC_LC: AUDIO_OBJECT_TYPE = 129;
pub const AUDIO_OBJECT_TYPE_AOT_MP2_SBR: AUDIO_OBJECT_TYPE = 132;
pub const AUDIO_OBJECT_TYPE_AOT_DRM_AAC: AUDIO_OBJECT_TYPE = 143;
pub const AUDIO_OBJECT_TYPE_AOT_DRM_SBR: AUDIO_OBJECT_TYPE = 144;
pub const AUDIO_OBJECT_TYPE_AOT_DRM_MPEG_PS: AUDIO_OBJECT_TYPE = 145;
pub const AUDIO_OBJECT_TYPE_AOT_DRM_SURROUND: AUDIO_OBJECT_TYPE = 146;
pub const AUDIO_OBJECT_TYPE_AOT_DRM_USAC: AUDIO_OBJECT_TYPE = 147;
pub type AUDIO_OBJECT_TYPE = ::std::os::raw::c_int;
pub const CHANNEL_MODE_MODE_INVALID: CHANNEL_MODE = -1;
pub const CHANNEL_MODE_MODE_UNKNOWN: CHANNEL_MODE = 0;
pub const CHANNEL_MODE_MODE_1: CHANNEL_MODE = 1;
pub const CHANNEL_MODE_MODE_2: CHANNEL_MODE = 2;
pub const CHANNEL_MODE_MODE_1_2: CHANNEL_MODE = 3;
pub const CHANNEL_MODE_MODE_1_2_1: CHANNEL_MODE = 4;
pub const CHANNEL_MODE_MODE_1_2_2: CHANNEL_MODE = 5;
pub const CHANNEL_MODE_MODE_1_2_2_1: CHANNEL_MODE = 6;
pub const CHANNEL_MODE_MODE_1_2_2_2_1: CHANNEL_MODE = 7;
pub const CHANNEL_MODE_MODE_6_1: CHANNEL_MODE = 11;
pub const CHANNEL_MODE_MODE_7_1_BACK: CHANNEL_MODE = 12;
pub const CHANNEL_MODE_MODE_7_1_TOP_FRONT: CHANNEL_MODE = 14;
pub const CHANNEL_MODE_MODE_7_1_REAR_SURROUND: CHANNEL_MODE = 33;
pub const CHANNEL_MODE_MODE_7_1_FRONT_CENTER: CHANNEL_MODE = 34;
pub const CHANNEL_MODE_MODE_212: CHANNEL_MODE = 128;
pub type CHANNEL_MODE = ::std::os::raw::c_int;
pub const AUDIO_CHANNEL_TYPE_ACT_NONE: AUDIO_CHANNEL_TYPE = 0;
pub const AUDIO_CHANNEL_TYPE_ACT_FRONT: AUDIO_CHANNEL_TYPE = 1;
pub const AUDIO_CHANNEL_TYPE_ACT_SIDE: AUDIO_CHANNEL_TYPE = 2;
pub const AUDIO_CHANNEL_TYPE_ACT_BACK: AUDIO_CHANNEL_TYPE = 3;
pub const AUDIO_CHANNEL_TYPE_ACT_LFE: AUDIO_CHANNEL_TYPE = 4;
pub const AUDIO_CHANNEL_TYPE_ACT_TOP: AUDIO_CHANNEL_TYPE = 16;
pub const AUDIO_CHANNEL_TYPE_ACT_FRONT_TOP: AUDIO_CHANNEL_TYPE = 17;
pub const AUDIO_CHANNEL_TYPE_ACT_SIDE_TOP: AUDIO_CHANNEL_TYPE = 18;
pub const AUDIO_CHANNEL_TYPE_ACT_BACK_TOP: AUDIO_CHANNEL_TYPE = 19;
pub const AUDIO_CHANNEL_TYPE_ACT_BOTTOM: AUDIO_CHANNEL_TYPE = 32;
pub const AUDIO_CHANNEL_TYPE_ACT_FRONT_BOTTOM: AUDIO_CHANNEL_TYPE = 33;
pub const AUDIO_CHANNEL_TYPE_ACT_SIDE_BOTTOM: AUDIO_CHANNEL_TYPE = 34;
pub const AUDIO_CHANNEL_TYPE_ACT_BACK_BOTTOM: AUDIO_CHANNEL_TYPE = 35;
pub type AUDIO_CHANNEL_TYPE = ::std::os::raw::c_uint;
pub const SBR_PS_SIGNALING_SIG_UNKNOWN: SBR_PS_SIGNALING = -1;
pub const SBR_PS_SIGNALING_SIG_IMPLICIT: SBR_PS_SIGNALING = 0;
pub const SBR_PS_SIGNALING_SIG_EXPLICIT_BW_COMPATIBLE: SBR_PS_SIGNALING = 1;
pub const SBR_PS_SIGNALING_SIG_EXPLICIT_HIERARCHICAL: SBR_PS_SIGNALING = 2;
pub type SBR_PS_SIGNALING = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CODER_CONFIG {
    pub aot: AUDIO_OBJECT_TYPE,
    pub extAOT: AUDIO_OBJECT_TYPE,
    pub channelMode: CHANNEL_MODE,
    pub channelConfigZero: UCHAR,
    pub samplingRate: INT,
    pub extSamplingRate: INT,
    pub downscaleSamplingRate: INT,
    pub bitRate: INT,
    pub samplesPerFrame: ::std::os::raw::c_int,
    pub noChannels: ::std::os::raw::c_int,
    pub bitsFrame: ::std::os::raw::c_int,
    pub nSubFrames: ::std::os::raw::c_int,
    pub BSACnumOfSubFrame: ::std::os::raw::c_int,
    pub BSAClayerLength: ::std::os::raw::c_int,
    pub flags: UINT,
    pub matrixMixdownA: UCHAR,
    pub headerPeriod: UCHAR,
    pub stereoConfigIndex: UCHAR,
    pub sbrMode: UCHAR,
    pub sbrSignaling: SBR_PS_SIGNALING,
    pub rawConfig: [UCHAR; 64usize],
    pub rawConfigBits: ::std::os::raw::c_int,
    pub sbrPresent: UCHAR,
    pub psPresent: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CODER_CONFIG"][::std::mem::size_of::<CODER_CONFIG>() - 140usize];
    ["Alignment of CODER_CONFIG"][::std::mem::align_of::<CODER_CONFIG>() - 4usize];
    ["Offset of field: CODER_CONFIG::aot"][::std::mem::offset_of!(CODER_CONFIG, aot) - 0usize];
    ["Offset of field: CODER_CONFIG::extAOT"]
        [::std::mem::offset_of!(CODER_CONFIG, extAOT) - 4usize];
    ["Offset of field: CODER_CONFIG::channelMode"]
        [::std::mem::offset_of!(CODER_CONFIG, channelMode) - 8usize];
    ["Offset of field: CODER_CONFIG::channelConfigZero"]
        [::std::mem::offset_of!(CODER_CONFIG, channelConfigZero) - 12usize];
    ["Offset of field: CODER_CONFIG::samplingRate"]
        [::std::mem::offset_of!(CODER_CONFIG, samplingRate) - 16usize];
    ["Offset of field: CODER_CONFIG::extSamplingRate"]
        [::std::mem::offset_of!(CODER_CONFIG, extSamplingRate) - 20usize];
    ["Offset of field: CODER_CONFIG::downscaleSamplingRate"]
        [::std::mem::offset_of!(CODER_CONFIG, downscaleSamplingRate) - 24usize];
    ["Offset of field: CODER_CONFIG::bitRate"]
        [::std::mem::offset_of!(CODER_CONFIG, bitRate) - 28usize];
    ["Offset of field: CODER_CONFIG::samplesPerFrame"]
        [::std::mem::offset_of!(CODER_CONFIG, samplesPerFrame) - 32usize];
    ["Offset of field: CODER_CONFIG::noChannels"]
        [::std::mem::offset_of!(CODER_CONFIG, noChannels) - 36usize];
    ["Offset of field: CODER_CONFIG::bitsFrame"]
        [::std::mem::offset_of!(CODER_CONFIG, bitsFrame) - 40usize];
    ["Offset of field: CODER_CONFIG::nSubFrames"]
        [::std::mem::offset_of!(CODER_CONFIG, nSubFrames) - 44usize];
    ["Offset of field: CODER_CONFIG::BSACnumOfSubFrame"]
        [::std::mem::offset_of!(CODER_CONFIG, BSACnumOfSubFrame) - 48usize];
    ["Offset of field: CODER_CONFIG::BSAClayerLength"]
        [::std::mem::offset_of!(CODER_CONFIG, BSAClayerLength) - 52usize];
    ["Offset of field: CODER_CONFIG::flags"][::std::mem::offset_of!(CODER_CONFIG, flags) - 56usize];
    ["Offset of field: CODER_CONFIG::matrixMixdownA"]
        [::std::mem::offset_of!(CODER_CONFIG, matrixMixdownA) - 60usize];
    ["Offset of field: CODER_CONFIG::headerPeriod"]
        [::std::mem::offset_of!(CODER_CONFIG, headerPeriod) - 61usize];
    ["Offset of field: CODER_CONFIG::stereoConfigIndex"]
        [::std::mem::offset_of!(CODER_CONFIG, stereoConfigIndex) - 62usize];
    ["Offset of field: CODER_CONFIG::sbrMode"]
        [::std::mem::offset_of!(CODER_CONFIG, sbrMode) - 63usize];
    ["Offset of field: CODER_CONFIG::sbrSignaling"]
        [::std::mem::offset_of!(CODER_CONFIG, sbrSignaling) - 64usize];
    ["Offset of field: CODER_CONFIG::rawConfig"]
        [::std::mem::offset_of!(CODER_CONFIG, rawConfig) - 68usize];
    ["Offset of field: CODER_CONFIG::rawConfigBits"]
        [::std::mem::offset_of!(CODER_CONFIG, rawConfigBits) - 132usize];
    ["Offset of field: CODER_CONFIG::sbrPresent"]
        [::std::mem::offset_of!(CODER_CONFIG, sbrPresent) - 136usize];
    ["Offset of field: CODER_CONFIG::psPresent"]
        [::std::mem::offset_of!(CODER_CONFIG, psPresent) - 137usize];
};
pub const MP4_ELEMENT_ID_ID_NONE: MP4_ELEMENT_ID = -1;
pub const MP4_ELEMENT_ID_ID_SCE: MP4_ELEMENT_ID = 0;
pub const MP4_ELEMENT_ID_ID_CPE: MP4_ELEMENT_ID = 1;
pub const MP4_ELEMENT_ID_ID_CCE: MP4_ELEMENT_ID = 2;
pub const MP4_ELEMENT_ID_ID_LFE: MP4_ELEMENT_ID = 3;
pub const MP4_ELEMENT_ID_ID_DSE: MP4_ELEMENT_ID = 4;
pub const MP4_ELEMENT_ID_ID_PCE: MP4_ELEMENT_ID = 5;
pub const MP4_ELEMENT_ID_ID_FIL: MP4_ELEMENT_ID = 6;
pub const MP4_ELEMENT_ID_ID_END: MP4_ELEMENT_ID = 7;
pub const MP4_ELEMENT_ID_ID_EXT: MP4_ELEMENT_ID = 8;
pub const MP4_ELEMENT_ID_ID_SCAL: MP4_ELEMENT_ID = 9;
pub const MP4_ELEMENT_ID_ID_USAC_SCE: MP4_ELEMENT_ID = 16;
pub const MP4_ELEMENT_ID_ID_USAC_CPE: MP4_ELEMENT_ID = 17;
pub const MP4_ELEMENT_ID_ID_USAC_LFE: MP4_ELEMENT_ID = 18;
pub const MP4_ELEMENT_ID_ID_USAC_EXT: MP4_ELEMENT_ID = 19;
pub const MP4_ELEMENT_ID_ID_USAC_END: MP4_ELEMENT_ID = 20;
pub const MP4_ELEMENT_ID_ID_LAST: MP4_ELEMENT_ID = 21;
pub type MP4_ELEMENT_ID = ::std::os::raw::c_int;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_FILL: CONFIG_EXT_ID = 0;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_DOWNMIX: CONFIG_EXT_ID = 1;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_LOUDNESS_INFO: CONFIG_EXT_ID = 2;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_AUDIOSCENE_INFO: CONFIG_EXT_ID = 3;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_HOA_MATRIX: CONFIG_EXT_ID = 4;
pub const CONFIG_EXT_ID_ID_CONFIG_EXT_SIG_GROUP_INFO: CONFIG_EXT_ID = 6;
pub type CONFIG_EXT_ID = ::std::os::raw::c_uint;
pub const EXT_PAYLOAD_TYPE_EXT_FIL: EXT_PAYLOAD_TYPE = 0;
pub const EXT_PAYLOAD_TYPE_EXT_FILL_DATA: EXT_PAYLOAD_TYPE = 1;
pub const EXT_PAYLOAD_TYPE_EXT_DATA_ELEMENT: EXT_PAYLOAD_TYPE = 2;
pub const EXT_PAYLOAD_TYPE_EXT_DATA_LENGTH: EXT_PAYLOAD_TYPE = 3;
pub const EXT_PAYLOAD_TYPE_EXT_UNI_DRC: EXT_PAYLOAD_TYPE = 4;
pub const EXT_PAYLOAD_TYPE_EXT_LDSAC_DATA: EXT_PAYLOAD_TYPE = 9;
pub const EXT_PAYLOAD_TYPE_EXT_SAOC_DATA: EXT_PAYLOAD_TYPE = 10;
pub const EXT_PAYLOAD_TYPE_EXT_DYNAMIC_RANGE: EXT_PAYLOAD_TYPE = 11;
pub const EXT_PAYLOAD_TYPE_EXT_SAC_DATA: EXT_PAYLOAD_TYPE = 12;
pub const EXT_PAYLOAD_TYPE_EXT_SBR_DATA: EXT_PAYLOAD_TYPE = 13;
pub const EXT_PAYLOAD_TYPE_EXT_SBR_DATA_CRC: EXT_PAYLOAD_TYPE = 14;
pub type EXT_PAYLOAD_TYPE = ::std::os::raw::c_uint;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_FILL: USAC_EXT_ELEMENT_TYPE = 0;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_MPEGS: USAC_EXT_ELEMENT_TYPE = 1;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_SAOC: USAC_EXT_ELEMENT_TYPE = 2;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_AUDIOPREROLL: USAC_EXT_ELEMENT_TYPE = 3;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_UNI_DRC: USAC_EXT_ELEMENT_TYPE = 4;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_OBJ_METADATA: USAC_EXT_ELEMENT_TYPE = 5;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_SAOC_3D: USAC_EXT_ELEMENT_TYPE = 6;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_HOA: USAC_EXT_ELEMENT_TYPE = 7;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_FMT_CNVRTR: USAC_EXT_ELEMENT_TYPE = 8;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_MCT: USAC_EXT_ELEMENT_TYPE = 9;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_ENHANCED_OBJ_METADATA: USAC_EXT_ELEMENT_TYPE = 13;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_VR_METADATA: USAC_EXT_ELEMENT_TYPE = 129;
pub const USAC_EXT_ELEMENT_TYPE_ID_EXT_ELE_UNKNOWN: USAC_EXT_ELEMENT_TYPE = 255;
pub type USAC_EXT_ELEMENT_TYPE = ::std::os::raw::c_uint;
pub const TP_CONFIG_TYPE_TC_NOTHING: TP_CONFIG_TYPE = 0;
pub const TP_CONFIG_TYPE_TC_RAW_ADTS: TP_CONFIG_TYPE = 2;
pub const TP_CONFIG_TYPE_TC_RAW_LATM_MCP1: TP_CONFIG_TYPE = 6;
pub const TP_CONFIG_TYPE_TC_RAW_SDC: TP_CONFIG_TYPE = 21;
pub type TP_CONFIG_TYPE = ::std::os::raw::c_uint;
pub const FDK_MODULE_ID_FDK_NONE: FDK_MODULE_ID = 0;
pub const FDK_MODULE_ID_FDK_TOOLS: FDK_MODULE_ID = 1;
pub const FDK_MODULE_ID_FDK_SYSLIB: FDK_MODULE_ID = 2;
pub const FDK_MODULE_ID_FDK_AACDEC: FDK_MODULE_ID = 3;
pub const FDK_MODULE_ID_FDK_AACENC: FDK_MODULE_ID = 4;
pub const FDK_MODULE_ID_FDK_SBRDEC: FDK_MODULE_ID = 5;
pub const FDK_MODULE_ID_FDK_SBRENC: FDK_MODULE_ID = 6;
pub const FDK_MODULE_ID_FDK_TPDEC: FDK_MODULE_ID = 7;
pub const FDK_MODULE_ID_FDK_TPENC: FDK_MODULE_ID = 8;
pub const FDK_MODULE_ID_FDK_MPSDEC: FDK_MODULE_ID = 9;
pub const FDK_MODULE_ID_FDK_MPEGFILEREAD: FDK_MODULE_ID = 10;
pub const FDK_MODULE_ID_FDK_MPEGFILEWRITE: FDK_MODULE_ID = 11;
pub const FDK_MODULE_ID_FDK_PCMDMX: FDK_MODULE_ID = 31;
pub const FDK_MODULE_ID_FDK_MPSENC: FDK_MODULE_ID = 34;
pub const FDK_MODULE_ID_FDK_TDLIMIT: FDK_MODULE_ID = 35;
pub const FDK_MODULE_ID_FDK_UNIDRCDEC: FDK_MODULE_ID = 38;
pub const FDK_MODULE_ID_FDK_MODULE_LAST: FDK_MODULE_ID = 39;
pub type FDK_MODULE_ID = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LIB_INFO {
    pub title: *const ::std::os::raw::c_char,
    pub build_date: *const ::std::os::raw::c_char,
    pub build_time: *const ::std::os::raw::c_char,
    pub module_id: FDK_MODULE_ID,
    pub version: INT,
    pub flags: UINT,
    pub versionStr: [::std::os::raw::c_char; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of LIB_INFO"][::std::mem::size_of::<LIB_INFO>() - 72usize];
    ["Alignment of LIB_INFO"][::std::mem::align_of::<LIB_INFO>() - 8usize];
    ["Offset of field: LIB_INFO::title"][::std::mem::offset_of!(LIB_INFO, title) - 0usize];
    ["Offset of field: LIB_INFO::build_date"]
        [::std::mem::offset_of!(LIB_INFO, build_date) - 8usize];
    ["Offset of field: LIB_INFO::build_time"]
        [::std::mem::offset_of!(LIB_INFO, build_time) - 16usize];
    ["Offset of field: LIB_INFO::module_id"][::std::mem::offset_of!(LIB_INFO, module_id) - 24usize];
    ["Offset of field: LIB_INFO::version"][::std::mem::offset_of!(LIB_INFO, version) - 28usize];
    ["Offset of field: LIB_INFO::flags"][::std::mem::offset_of!(LIB_INFO, flags) - 32usize];
    ["Offset of field: LIB_INFO::versionStr"]
        [::std::mem::offset_of!(LIB_INFO, versionStr) - 36usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FDK_bufDescr {
    pub ppBase: *mut *mut ::std::os::raw::c_void,
    pub pBufSize: *mut UINT,
    pub pEleSize: *mut UINT,
    pub pBufType: *mut UINT,
    pub numBufs: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FDK_bufDescr"][::std::mem::size_of::<FDK_bufDescr>() - 40usize];
    ["Alignment of FDK_bufDescr"][::std::mem::align_of::<FDK_bufDescr>() - 8usize];
    ["Offset of field: FDK_bufDescr::ppBase"]
        [::std::mem::offset_of!(FDK_bufDescr, ppBase) - 0usize];
    ["Offset of field: FDK_bufDescr::pBufSize"]
        [::std::mem::offset_of!(FDK_bufDescr, pBufSize) - 8usize];
    ["Offset of field: FDK_bufDescr::pEleSize"]
        [::std::mem::offset_of!(FDK_bufDescr, pEleSize) - 16usize];
    ["Offset of field: FDK_bufDescr::pBufType"]
        [::std::mem::offset_of!(FDK_bufDescr, pBufType) - 24usize];
    ["Offset of field: FDK_bufDescr::numBufs"]
        [::std::mem::offset_of!(FDK_bufDescr, numBufs) - 32usize];
};
pub const AACENC_ERROR_AACENC_OK: AACENC_ERROR = 0;
pub const AACENC_ERROR_AACENC_INVALID_HANDLE: AACENC_ERROR = 32;
pub const AACENC_ERROR_AACENC_MEMORY_ERROR: AACENC_ERROR = 33;
pub const AACENC_ERROR_AACENC_UNSUPPORTED_PARAMETER: AACENC_ERROR = 34;
pub const AACENC_ERROR_AACENC_INVALID_CONFIG: AACENC_ERROR = 35;
pub const AACENC_ERROR_AACENC_INIT_ERROR: AACENC_ERROR = 64;
pub const AACENC_ERROR_AACENC_INIT_AAC_ERROR: AACENC_ERROR = 65;
pub const AACENC_ERROR_AACENC_INIT_SBR_ERROR: AACENC_ERROR = 66;
pub const AACENC_ERROR_AACENC_INIT_TP_ERROR: AACENC_ERROR = 67;
pub const AACENC_ERROR_AACENC_INIT_META_ERROR: AACENC_ERROR = 68;
pub const AACENC_ERROR_AACENC_INIT_MPS_ERROR: AACENC_ERROR = 69;
pub const AACENC_ERROR_AACENC_ENCODE_ERROR: AACENC_ERROR = 96;
pub const AACENC_ERROR_AACENC_ENCODE_EOF: AACENC_ERROR = 128;
pub type AACENC_ERROR = ::std::os::raw::c_uint;
pub const AACENC_BufferIdentifier_IN_AUDIO_DATA: AACENC_BufferIdentifier = 0;
pub const AACENC_BufferIdentifier_IN_ANCILLRY_DATA: AACENC_BufferIdentifier = 1;
pub const AACENC_BufferIdentifier_IN_METADATA_SETUP: AACENC_BufferIdentifier = 2;
pub const AACENC_BufferIdentifier_OUT_BITSTREAM_DATA: AACENC_BufferIdentifier = 3;
pub const AACENC_BufferIdentifier_OUT_AU_SIZES: AACENC_BufferIdentifier = 4;
pub type AACENC_BufferIdentifier = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENCODER {
    _unused: [u8; 0],
}
pub type HANDLE_AACENCODER = *mut AACENCODER;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_InfoStruct {
    pub maxOutBufBytes: UINT,
    pub maxAncBytes: UINT,
    pub inBufFillLevel: UINT,
    pub inputChannels: UINT,
    pub frameLength: UINT,
    pub nDelay: UINT,
    pub nDelayCore: UINT,
    pub confBuf: [UCHAR; 64usize],
    pub confSize: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_InfoStruct"][::std::mem::size_of::<AACENC_InfoStruct>() - 96usize];
    ["Alignment of AACENC_InfoStruct"][::std::mem::align_of::<AACENC_InfoStruct>() - 4usize];
    ["Offset of field: AACENC_InfoStruct::maxOutBufBytes"]
        [::std::mem::offset_of!(AACENC_InfoStruct, maxOutBufBytes) - 0usize];
    ["Offset of field: AACENC_InfoStruct::maxAncBytes"]
        [::std::mem::offset_of!(AACENC_InfoStruct, maxAncBytes) - 4usize];
    ["Offset of field: AACENC_InfoStruct::inBufFillLevel"]
        [::std::mem::offset_of!(AACENC_InfoStruct, inBufFillLevel) - 8usize];
    ["Offset of field: AACENC_InfoStruct::inputChannels"]
        [::std::mem::offset_of!(AACENC_InfoStruct, inputChannels) - 12usize];
    ["Offset of field: AACENC_InfoStruct::frameLength"]
        [::std::mem::offset_of!(AACENC_InfoStruct, frameLength) - 16usize];
    ["Offset of field: AACENC_InfoStruct::nDelay"]
        [::std::mem::offset_of!(AACENC_InfoStruct, nDelay) - 20usize];
    ["Offset of field: AACENC_InfoStruct::nDelayCore"]
        [::std::mem::offset_of!(AACENC_InfoStruct, nDelayCore) - 24usize];
    ["Offset of field: AACENC_InfoStruct::confBuf"]
        [::std::mem::offset_of!(AACENC_InfoStruct, confBuf) - 28usize];
    ["Offset of field: AACENC_InfoStruct::confSize"]
        [::std::mem::offset_of!(AACENC_InfoStruct, confSize) - 92usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_BufDesc {
    pub numBufs: INT,
    pub bufs: *mut *mut ::std::os::raw::c_void,
    pub bufferIdentifiers: *mut INT,
    pub bufSizes: *mut INT,
    pub bufElSizes: *mut INT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_BufDesc"][::std::mem::size_of::<AACENC_BufDesc>() - 40usize];
    ["Alignment of AACENC_BufDesc"][::std::mem::align_of::<AACENC_BufDesc>() - 8usize];
    ["Offset of field: AACENC_BufDesc::numBufs"]
        [::std::mem::offset_of!(AACENC_BufDesc, numBufs) - 0usize];
    ["Offset of field: AACENC_BufDesc::bufs"]
        [::std::mem::offset_of!(AACENC_BufDesc, bufs) - 8usize];
    ["Offset of field: AACENC_BufDesc::bufferIdentifiers"]
        [::std::mem::offset_of!(AACENC_BufDesc, bufferIdentifiers) - 16usize];
    ["Offset of field: AACENC_BufDesc::bufSizes"]
        [::std::mem::offset_of!(AACENC_BufDesc, bufSizes) - 24usize];
    ["Offset of field: AACENC_BufDesc::bufElSizes"]
        [::std::mem::offset_of!(AACENC_BufDesc, bufElSizes) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_InArgs {
    pub numInSamples: INT,
    pub numAncBytes: INT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_InArgs"][::std::mem::size_of::<AACENC_InArgs>() - 8usize];
    ["Alignment of AACENC_InArgs"][::std::mem::align_of::<AACENC_InArgs>() - 4usize];
    ["Offset of field: AACENC_InArgs::numInSamples"]
        [::std::mem::offset_of!(AACENC_InArgs, numInSamples) - 0usize];
    ["Offset of field: AACENC_InArgs::numAncBytes"]
        [::std::mem::offset_of!(AACENC_InArgs, numAncBytes) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_OutArgs {
    pub numOutBytes: INT,
    pub numInSamples: INT,
    pub numAncBytes: INT,
    pub bitResState: INT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_OutArgs"][::std::mem::size_of::<AACENC_OutArgs>() - 16usize];
    ["Alignment of AACENC_OutArgs"][::std::mem::align_of::<AACENC_OutArgs>() - 4usize];
    ["Offset of field: AACENC_OutArgs::numOutBytes"]
        [::std::mem::offset_of!(AACENC_OutArgs, numOutBytes) - 0usize];
    ["Offset of field: AACENC_OutArgs::numInSamples"]
        [::std::mem::offset_of!(AACENC_OutArgs, numInSamples) - 4usize];
    ["Offset of field: AACENC_OutArgs::numAncBytes"]
        [::std::mem::offset_of!(AACENC_OutArgs, numAncBytes) - 8usize];
    ["Offset of field: AACENC_OutArgs::bitResState"]
        [::std::mem::offset_of!(AACENC_OutArgs, bitResState) - 12usize];
};
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_NONE: AACENC_METADATA_DRC_PROFILE = 0;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_FILMSTANDARD:
    AACENC_METADATA_DRC_PROFILE = 1;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_FILMLIGHT: AACENC_METADATA_DRC_PROFILE =
    2;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_MUSICSTANDARD:
    AACENC_METADATA_DRC_PROFILE = 3;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_MUSICLIGHT: AACENC_METADATA_DRC_PROFILE =
    4;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_SPEECH: AACENC_METADATA_DRC_PROFILE = 5;
pub const AACENC_METADATA_DRC_PROFILE_AACENC_METADATA_DRC_NOT_PRESENT: AACENC_METADATA_DRC_PROFILE =
    256;
pub type AACENC_METADATA_DRC_PROFILE = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_MetaData {
    pub drc_profile: AACENC_METADATA_DRC_PROFILE,
    pub comp_profile: AACENC_METADATA_DRC_PROFILE,
    pub drc_TargetRefLevel: INT,
    pub comp_TargetRefLevel: INT,
    pub prog_ref_level_present: INT,
    pub prog_ref_level: INT,
    pub PCE_mixdown_idx_present: UCHAR,
    pub ETSI_DmxLvl_present: UCHAR,
    pub centerMixLevel: SCHAR,
    pub surroundMixLevel: SCHAR,
    pub dolbySurroundMode: UCHAR,
    pub drcPresentationMode: UCHAR,
    pub ExtMetaData: AACENC_MetaData__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AACENC_MetaData__bindgen_ty_1 {
    pub extAncDataEnable: UCHAR,
    pub extDownmixLevelEnable: UCHAR,
    pub extDownmixLevel_A: UCHAR,
    pub extDownmixLevel_B: UCHAR,
    pub dmxGainEnable: UCHAR,
    pub dmxGain5: INT,
    pub dmxGain2: INT,
    pub lfeDmxEnable: UCHAR,
    pub lfeDmxLevel: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_MetaData__bindgen_ty_1"]
        [::std::mem::size_of::<AACENC_MetaData__bindgen_ty_1>() - 20usize];
    ["Alignment of AACENC_MetaData__bindgen_ty_1"]
        [::std::mem::align_of::<AACENC_MetaData__bindgen_ty_1>() - 4usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::extAncDataEnable"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, extAncDataEnable) - 0usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::extDownmixLevelEnable"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, extDownmixLevelEnable) - 1usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::extDownmixLevel_A"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, extDownmixLevel_A) - 2usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::extDownmixLevel_B"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, extDownmixLevel_B) - 3usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::dmxGainEnable"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, dmxGainEnable) - 4usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::dmxGain5"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, dmxGain5) - 8usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::dmxGain2"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, dmxGain2) - 12usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::lfeDmxEnable"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, lfeDmxEnable) - 16usize];
    ["Offset of field: AACENC_MetaData__bindgen_ty_1::lfeDmxLevel"]
        [::std::mem::offset_of!(AACENC_MetaData__bindgen_ty_1, lfeDmxLevel) - 17usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AACENC_MetaData"][::std::mem::size_of::<AACENC_MetaData>() - 52usize];
    ["Alignment of AACENC_MetaData"][::std::mem::align_of::<AACENC_MetaData>() - 4usize];
    ["Offset of field: AACENC_MetaData::drc_profile"]
        [::std::mem::offset_of!(AACENC_MetaData, drc_profile) - 0usize];
    ["Offset of field: AACENC_MetaData::comp_profile"]
        [::std::mem::offset_of!(AACENC_MetaData, comp_profile) - 4usize];
    ["Offset of field: AACENC_MetaData::drc_TargetRefLevel"]
        [::std::mem::offset_of!(AACENC_MetaData, drc_TargetRefLevel) - 8usize];
    ["Offset of field: AACENC_MetaData::comp_TargetRefLevel"]
        [::std::mem::offset_of!(AACENC_MetaData, comp_TargetRefLevel) - 12usize];
    ["Offset of field: AACENC_MetaData::prog_ref_level_present"]
        [::std::mem::offset_of!(AACENC_MetaData, prog_ref_level_present) - 16usize];
    ["Offset of field: AACENC_MetaData::prog_ref_level"]
        [::std::mem::offset_of!(AACENC_MetaData, prog_ref_level) - 20usize];
    ["Offset of field: AACENC_MetaData::PCE_mixdown_idx_present"]
        [::std::mem::offset_of!(AACENC_MetaData, PCE_mixdown_idx_present) - 24usize];
    ["Offset of field: AACENC_MetaData::ETSI_DmxLvl_present"]
        [::std::mem::offset_of!(AACENC_MetaData, ETSI_DmxLvl_present) - 25usize];
    ["Offset of field: AACENC_MetaData::centerMixLevel"]
        [::std::mem::offset_of!(AACENC_MetaData, centerMixLevel) - 26usize];
    ["Offset of field: AACENC_MetaData::surroundMixLevel"]
        [::std::mem::offset_of!(AACENC_MetaData, surroundMixLevel) - 27usize];
    ["Offset of field: AACENC_MetaData::dolbySurroundMode"]
        [::std::mem::offset_of!(AACENC_MetaData, dolbySurroundMode) - 28usize];
    ["Offset of field: AACENC_MetaData::drcPresentationMode"]
        [::std::mem::offset_of!(AACENC_MetaData, drcPresentationMode) - 29usize];
    ["Offset of field: AACENC_MetaData::ExtMetaData"]
        [::std::mem::offset_of!(AACENC_MetaData, ExtMetaData) - 32usize];
};
pub const AACENC_CTRLFLAGS_AACENC_INIT_NONE: AACENC_CTRLFLAGS = 0;
pub const AACENC_CTRLFLAGS_AACENC_INIT_CONFIG: AACENC_CTRLFLAGS = 1;
pub const AACENC_CTRLFLAGS_AACENC_INIT_STATES: AACENC_CTRLFLAGS = 2;
pub const AACENC_CTRLFLAGS_AACENC_INIT_TRANSPORT: AACENC_CTRLFLAGS = 4096;
pub const AACENC_CTRLFLAGS_AACENC_RESET_INBUFFER: AACENC_CTRLFLAGS = 8192;
pub const AACENC_CTRLFLAGS_AACENC_INIT_ALL: AACENC_CTRLFLAGS = 65535;
pub type AACENC_CTRLFLAGS = ::std::os::raw::c_uint;
pub const AACENC_PARAM_AACENC_AOT: AACENC_PARAM = 256;
pub const AACENC_PARAM_AACENC_BITRATE: AACENC_PARAM = 257;
pub const AACENC_PARAM_AACENC_BITRATEMODE: AACENC_PARAM = 258;
pub const AACENC_PARAM_AACENC_SAMPLERATE: AACENC_PARAM = 259;
pub const AACENC_PARAM_AACENC_SBR_MODE: AACENC_PARAM = 260;
pub const AACENC_PARAM_AACENC_GRANULE_LENGTH: AACENC_PARAM = 261;
pub const AACENC_PARAM_AACENC_CHANNELMODE: AACENC_PARAM = 262;
pub const AACENC_PARAM_AACENC_CHANNELORDER: AACENC_PARAM = 263;
pub const AACENC_PARAM_AACENC_SBR_RATIO: AACENC_PARAM = 264;
pub const AACENC_PARAM_AACENC_AFTERBURNER: AACENC_PARAM = 512;
pub const AACENC_PARAM_AACENC_BANDWIDTH: AACENC_PARAM = 515;
pub const AACENC_PARAM_AACENC_PEAK_BITRATE: AACENC_PARAM = 519;
pub const AACENC_PARAM_AACENC_TRANSMUX: AACENC_PARAM = 768;
pub const AACENC_PARAM_AACENC_HEADER_PERIOD: AACENC_PARAM = 769;
pub const AACENC_PARAM_AACENC_SIGNALING_MODE: AACENC_PARAM = 770;
pub const AACENC_PARAM_AACENC_TPSUBFRAMES: AACENC_PARAM = 771;
pub const AACENC_PARAM_AACENC_AUDIOMUXVER: AACENC_PARAM = 772;
pub const AACENC_PARAM_AACENC_PROTECTION: AACENC_PARAM = 774;
pub const AACENC_PARAM_AACENC_ANCILLARY_BITRATE: AACENC_PARAM = 1280;
pub const AACENC_PARAM_AACENC_METADATA_MODE: AACENC_PARAM = 1536;
pub const AACENC_PARAM_AACENC_CONTROL_STATE: AACENC_PARAM = 65280;
pub const AACENC_PARAM_AACENC_NONE: AACENC_PARAM = 65535;
pub type AACENC_PARAM = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn aacEncOpen(
        phAacEncoder: *mut HANDLE_AACENCODER,
        encModules: UINT,
        maxChannels: UINT,
    ) -> AACENC_ERROR;
}
unsafe extern "C" {
    pub fn aacEncClose(phAacEncoder: *mut HANDLE_AACENCODER) -> AACENC_ERROR;
}
unsafe extern "C" {
    pub fn aacEncEncode(
        hAacEncoder: HANDLE_AACENCODER,
        inBufDesc: *const AACENC_BufDesc,
        outBufDesc: *const AACENC_BufDesc,
        inargs: *const AACENC_InArgs,
        outargs: *mut AACENC_OutArgs,
    ) -> AACENC_ERROR;
}
unsafe extern "C" {
    pub fn aacEncInfo(
        hAacEncoder: HANDLE_AACENCODER,
        pInfo: *mut AACENC_InfoStruct,
    ) -> AACENC_ERROR;
}
unsafe extern "C" {
    pub fn aacEncoder_SetParam(
        hAacEncoder: HANDLE_AACENCODER,
        param: AACENC_PARAM,
        value: UINT,
    ) -> AACENC_ERROR;
}
unsafe extern "C" {
    pub fn aacEncoder_GetParam(hAacEncoder: HANDLE_AACENCODER, param: AACENC_PARAM) -> UINT;
}
unsafe extern "C" {
    pub fn aacEncGetLibInfo(info: *mut LIB_INFO) -> AACENC_ERROR;
}
pub const AAC_DECODER_ERROR_AAC_DEC_OK: AAC_DECODER_ERROR = 0;
pub const AAC_DECODER_ERROR_AAC_DEC_OUT_OF_MEMORY: AAC_DECODER_ERROR = 2;
pub const AAC_DECODER_ERROR_AAC_DEC_UNKNOWN: AAC_DECODER_ERROR = 5;
pub const AAC_DECODER_ERROR_aac_dec_sync_error_start: AAC_DECODER_ERROR = 4096;
pub const AAC_DECODER_ERROR_AAC_DEC_TRANSPORT_SYNC_ERROR: AAC_DECODER_ERROR = 4097;
pub const AAC_DECODER_ERROR_AAC_DEC_NOT_ENOUGH_BITS: AAC_DECODER_ERROR = 4098;
pub const AAC_DECODER_ERROR_aac_dec_sync_error_end: AAC_DECODER_ERROR = 8191;
pub const AAC_DECODER_ERROR_aac_dec_init_error_start: AAC_DECODER_ERROR = 8192;
pub const AAC_DECODER_ERROR_AAC_DEC_INVALID_HANDLE: AAC_DECODER_ERROR = 8193;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_AOT: AAC_DECODER_ERROR = 8194;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_FORMAT: AAC_DECODER_ERROR = 8195;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_ER_FORMAT: AAC_DECODER_ERROR = 8196;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_EPCONFIG: AAC_DECODER_ERROR = 8197;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_MULTILAYER: AAC_DECODER_ERROR = 8198;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_CHANNELCONFIG: AAC_DECODER_ERROR = 8199;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_SAMPLINGRATE: AAC_DECODER_ERROR = 8200;
pub const AAC_DECODER_ERROR_AAC_DEC_INVALID_SBR_CONFIG: AAC_DECODER_ERROR = 8201;
pub const AAC_DECODER_ERROR_AAC_DEC_SET_PARAM_FAIL: AAC_DECODER_ERROR = 8202;
pub const AAC_DECODER_ERROR_AAC_DEC_NEED_TO_RESTART: AAC_DECODER_ERROR = 8203;
pub const AAC_DECODER_ERROR_AAC_DEC_OUTPUT_BUFFER_TOO_SMALL: AAC_DECODER_ERROR = 8204;
pub const AAC_DECODER_ERROR_aac_dec_init_error_end: AAC_DECODER_ERROR = 12287;
pub const AAC_DECODER_ERROR_aac_dec_decode_error_start: AAC_DECODER_ERROR = 16384;
pub const AAC_DECODER_ERROR_AAC_DEC_TRANSPORT_ERROR: AAC_DECODER_ERROR = 16385;
pub const AAC_DECODER_ERROR_AAC_DEC_PARSE_ERROR: AAC_DECODER_ERROR = 16386;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_EXTENSION_PAYLOAD: AAC_DECODER_ERROR = 16387;
pub const AAC_DECODER_ERROR_AAC_DEC_DECODE_FRAME_ERROR: AAC_DECODER_ERROR = 16388;
pub const AAC_DECODER_ERROR_AAC_DEC_CRC_ERROR: AAC_DECODER_ERROR = 16389;
pub const AAC_DECODER_ERROR_AAC_DEC_INVALID_CODE_BOOK: AAC_DECODER_ERROR = 16390;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_PREDICTION: AAC_DECODER_ERROR = 16391;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_CCE: AAC_DECODER_ERROR = 16392;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_LFE: AAC_DECODER_ERROR = 16393;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_GAIN_CONTROL_DATA: AAC_DECODER_ERROR = 16394;
pub const AAC_DECODER_ERROR_AAC_DEC_UNSUPPORTED_SBA: AAC_DECODER_ERROR = 16395;
pub const AAC_DECODER_ERROR_AAC_DEC_TNS_READ_ERROR: AAC_DECODER_ERROR = 16396;
pub const AAC_DECODER_ERROR_AAC_DEC_RVLC_ERROR: AAC_DECODER_ERROR = 16397;
pub const AAC_DECODER_ERROR_aac_dec_decode_error_end: AAC_DECODER_ERROR = 20479;
pub const AAC_DECODER_ERROR_aac_dec_anc_data_error_start: AAC_DECODER_ERROR = 32768;
pub const AAC_DECODER_ERROR_AAC_DEC_ANC_DATA_ERROR: AAC_DECODER_ERROR = 32769;
pub const AAC_DECODER_ERROR_AAC_DEC_TOO_SMALL_ANC_BUFFER: AAC_DECODER_ERROR = 32770;
pub const AAC_DECODER_ERROR_AAC_DEC_TOO_MANY_ANC_ELEMENTS: AAC_DECODER_ERROR = 32771;
pub const AAC_DECODER_ERROR_aac_dec_anc_data_error_end: AAC_DECODER_ERROR = 36863;
pub type AAC_DECODER_ERROR = ::std::os::raw::c_uint;
pub const AAC_MD_PROFILE_AAC_MD_PROFILE_MPEG_STANDARD: AAC_MD_PROFILE = 0;
pub const AAC_MD_PROFILE_AAC_MD_PROFILE_MPEG_LEGACY: AAC_MD_PROFILE = 1;
pub const AAC_MD_PROFILE_AAC_MD_PROFILE_MPEG_LEGACY_PRIO: AAC_MD_PROFILE = 2;
pub const AAC_MD_PROFILE_AAC_MD_PROFILE_ARIB_JAPAN: AAC_MD_PROFILE = 3;
pub type AAC_MD_PROFILE = ::std::os::raw::c_uint;
pub const AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS_AAC_DRC_PARAMETER_HANDLING_DISABLED:
    AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS = -1;
pub const AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS_AAC_DRC_PARAMETER_HANDLING_ENABLED:
    AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS = 0;
pub const AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS_AAC_DRC_PRESENTATION_MODE_1_DEFAULT:
    AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS = 1;
pub const AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS_AAC_DRC_PRESENTATION_MODE_2_DEFAULT:
    AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS = 2;
pub type AAC_DRC_DEFAULT_PRESENTATION_MODE_OPTIONS = ::std::os::raw::c_int;
pub const AACDEC_PARAM_AAC_PCM_DUAL_CHANNEL_OUTPUT_MODE: AACDEC_PARAM = 2;
pub const AACDEC_PARAM_AAC_PCM_OUTPUT_CHANNEL_MAPPING: AACDEC_PARAM = 3;
pub const AACDEC_PARAM_AAC_PCM_LIMITER_ENABLE: AACDEC_PARAM = 4;
pub const AACDEC_PARAM_AAC_PCM_LIMITER_ATTACK_TIME: AACDEC_PARAM = 5;
pub const AACDEC_PARAM_AAC_PCM_LIMITER_RELEAS_TIME: AACDEC_PARAM = 6;
pub const AACDEC_PARAM_AAC_PCM_MIN_OUTPUT_CHANNELS: AACDEC_PARAM = 17;
pub const AACDEC_PARAM_AAC_PCM_MAX_OUTPUT_CHANNELS: AACDEC_PARAM = 18;
pub const AACDEC_PARAM_AAC_METADATA_PROFILE: AACDEC_PARAM = 32;
pub const AACDEC_PARAM_AAC_METADATA_EXPIRY_TIME: AACDEC_PARAM = 33;
pub const AACDEC_PARAM_AAC_CONCEAL_METHOD: AACDEC_PARAM = 256;
pub const AACDEC_PARAM_AAC_DRC_BOOST_FACTOR: AACDEC_PARAM = 512;
pub const AACDEC_PARAM_AAC_DRC_ATTENUATION_FACTOR: AACDEC_PARAM = 513;
pub const AACDEC_PARAM_AAC_DRC_REFERENCE_LEVEL: AACDEC_PARAM = 514;
pub const AACDEC_PARAM_AAC_DRC_HEAVY_COMPRESSION: AACDEC_PARAM = 515;
pub const AACDEC_PARAM_AAC_DRC_DEFAULT_PRESENTATION_MODE: AACDEC_PARAM = 516;
pub const AACDEC_PARAM_AAC_DRC_ENC_TARGET_LEVEL: AACDEC_PARAM = 517;
pub const AACDEC_PARAM_AAC_UNIDRC_SET_EFFECT: AACDEC_PARAM = 518;
pub const AACDEC_PARAM_AAC_UNIDRC_ALBUM_MODE: AACDEC_PARAM = 519;
pub const AACDEC_PARAM_AAC_QMF_LOWPOWER: AACDEC_PARAM = 768;
pub const AACDEC_PARAM_AAC_TPDEC_CLEAR_BUFFER: AACDEC_PARAM = 1539;
pub type AACDEC_PARAM = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CStreamInfo {
    pub sampleRate: INT,
    pub frameSize: INT,
    pub numChannels: INT,
    pub pChannelType: *mut AUDIO_CHANNEL_TYPE,
    pub pChannelIndices: *mut UCHAR,
    pub aacSampleRate: INT,
    pub profile: INT,
    pub aot: AUDIO_OBJECT_TYPE,
    pub channelConfig: INT,
    pub bitRate: INT,
    pub aacSamplesPerFrame: INT,
    pub aacNumChannels: INT,
    pub extAot: AUDIO_OBJECT_TYPE,
    pub extSamplingRate: INT,
    pub outputDelay: UINT,
    pub flags: UINT,
    pub epConfig: SCHAR,
    pub numLostAccessUnits: INT,
    pub numTotalBytes: INT64,
    pub numBadBytes: INT64,
    pub numTotalAccessUnits: INT64,
    pub numBadAccessUnits: INT64,
    pub drcProgRefLev: SCHAR,
    pub drcPresMode: SCHAR,
    pub outputLoudness: INT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CStreamInfo"][::std::mem::size_of::<CStreamInfo>() - 128usize];
    ["Alignment of CStreamInfo"][::std::mem::align_of::<CStreamInfo>() - 8usize];
    ["Offset of field: CStreamInfo::sampleRate"]
        [::std::mem::offset_of!(CStreamInfo, sampleRate) - 0usize];
    ["Offset of field: CStreamInfo::frameSize"]
        [::std::mem::offset_of!(CStreamInfo, frameSize) - 4usize];
    ["Offset of field: CStreamInfo::numChannels"]
        [::std::mem::offset_of!(CStreamInfo, numChannels) - 8usize];
    ["Offset of field: CStreamInfo::pChannelType"]
        [::std::mem::offset_of!(CStreamInfo, pChannelType) - 16usize];
    ["Offset of field: CStreamInfo::pChannelIndices"]
        [::std::mem::offset_of!(CStreamInfo, pChannelIndices) - 24usize];
    ["Offset of field: CStreamInfo::aacSampleRate"]
        [::std::mem::offset_of!(CStreamInfo, aacSampleRate) - 32usize];
    ["Offset of field: CStreamInfo::profile"]
        [::std::mem::offset_of!(CStreamInfo, profile) - 36usize];
    ["Offset of field: CStreamInfo::aot"][::std::mem::offset_of!(CStreamInfo, aot) - 40usize];
    ["Offset of field: CStreamInfo::channelConfig"]
        [::std::mem::offset_of!(CStreamInfo, channelConfig) - 44usize];
    ["Offset of field: CStreamInfo::bitRate"]
        [::std::mem::offset_of!(CStreamInfo, bitRate) - 48usize];
    ["Offset of field: CStreamInfo::aacSamplesPerFrame"]
        [::std::mem::offset_of!(CStreamInfo, aacSamplesPerFrame) - 52usize];
    ["Offset of field: CStreamInfo::aacNumChannels"]
        [::std::mem::offset_of!(CStreamInfo, aacNumChannels) - 56usize];
    ["Offset of field: CStreamInfo::extAot"][::std::mem::offset_of!(CStreamInfo, extAot) - 60usize];
    ["Offset of field: CStreamInfo::extSamplingRate"]
        [::std::mem::offset_of!(CStreamInfo, extSamplingRate) - 64usize];
    ["Offset of field: CStreamInfo::outputDelay"]
        [::std::mem::offset_of!(CStreamInfo, outputDelay) - 68usize];
    ["Offset of field: CStreamInfo::flags"][::std::mem::offset_of!(CStreamInfo, flags) - 72usize];
    ["Offset of field: CStreamInfo::epConfig"]
        [::std::mem::offset_of!(CStreamInfo, epConfig) - 76usize];
    ["Offset of field: CStreamInfo::numLostAccessUnits"]
        [::std::mem::offset_of!(CStreamInfo, numLostAccessUnits) - 80usize];
    ["Offset of field: CStreamInfo::numTotalBytes"]
        [::std::mem::offset_of!(CStreamInfo, numTotalBytes) - 88usize];
    ["Offset of field: CStreamInfo::numBadBytes"]
        [::std::mem::offset_of!(CStreamInfo, numBadBytes) - 96usize];
    ["Offset of field: CStreamInfo::numTotalAccessUnits"]
        [::std::mem::offset_of!(CStreamInfo, numTotalAccessUnits) - 104usize];
    ["Offset of field: CStreamInfo::numBadAccessUnits"]
        [::std::mem::offset_of!(CStreamInfo, numBadAccessUnits) - 112usize];
    ["Offset of field: CStreamInfo::drcProgRefLev"]
        [::std::mem::offset_of!(CStreamInfo, drcProgRefLev) - 120usize];
    ["Offset of field: CStreamInfo::drcPresMode"]
        [::std::mem::offset_of!(CStreamInfo, drcPresMode) - 121usize];
    ["Offset of field: CStreamInfo::outputLoudness"]
        [::std::mem::offset_of!(CStreamInfo, outputLoudness) - 124usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AAC_DECODER_INSTANCE {
    _unused: [u8; 0],
}
pub type HANDLE_AACDECODER = *mut AAC_DECODER_INSTANCE;
unsafe extern "C" {
    pub fn aacDecoder_AncDataInit(
        self_: HANDLE_AACDECODER,
        buffer: *mut UCHAR,
        size: ::std::os::raw::c_int,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_AncDataGet(
        self_: HANDLE_AACDECODER,
        index: ::std::os::raw::c_int,
        ptr: *mut *mut UCHAR,
        size: *mut ::std::os::raw::c_int,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_SetParam(
        self_: HANDLE_AACDECODER,
        param: AACDEC_PARAM,
        value: INT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_GetFreeBytes(
        self_: HANDLE_AACDECODER,
        pFreeBytes: *mut UINT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_Open(transportFmt: TRANSPORT_TYPE, nrOfLayers: UINT) -> HANDLE_AACDECODER;
}
unsafe extern "C" {
    pub fn aacDecoder_ConfigRaw(
        self_: HANDLE_AACDECODER,
        conf: *mut *mut UCHAR,
        length: *const UINT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_RawISOBMFFData(
        self_: HANDLE_AACDECODER,
        buffer: *mut UCHAR,
        length: UINT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_Fill(
        self_: HANDLE_AACDECODER,
        pBuffer: *mut *mut UCHAR,
        bufferSize: *const UINT,
        bytesValid: *mut UINT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_DecodeFrame(
        self_: HANDLE_AACDECODER,
        pTimeData: *mut INT_PCM,
        timeDataSize: INT,
        flags: UINT,
    ) -> AAC_DECODER_ERROR;
}
unsafe extern "C" {
    pub fn aacDecoder_Close(self_: HANDLE_AACDECODER);
}
unsafe extern "C" {
    pub fn aacDecoder_GetStreamInfo(self_: HANDLE_AACDECODER) -> *mut CStreamInfo;
}
unsafe extern "C" {
    pub fn aacDecoder_GetLibInfo(info: *mut LIB_INFO) -> INT;
}
