//! @generated by gen-version.sh from the fdk-aac 2.0.3 sources — do not edit.
//!
//! fdk-aac reports no package version at runtime. These are the encoder and decoder
//! *module* versions, lifted from libAACenc/src/aacenc_lib.cpp and
//! libAACdec/src/aacdecoder_lib.cpp, and they are what `aacEncGetLibInfo` and
//! `aacDecoder_GetLibInfo` fill in. Asserting the linked archive reports these is this
//! crate's stand-in for `opus_get_version_string()`.

/// The fdk-aac release these bindings and the published archives were built from.
pub const FDK_AAC_VERSION: &str = "2.0.3";

/// `aacEncGetLibInfo` must report this for the "AAC Encoder" module.
pub const ENCODER_LIB_VERSION: (u32, u32, u32) = (4, 0, 1);

/// `aacDecoder_GetLibInfo` must report this for the "AAC Decoder Lib" module.
pub const DECODER_LIB_VERSION: (u32, u32, u32) = (3, 2, 0);

/// The packing `LIB_VERSION` uses, from libSYS/include/FDK_audio.h:703:
///
/// ```text
/// (lev0 << 24 & 0xff000000) | (lev1 << 16 & 0x00ff0000) | (lev2 << 8 & 0x0000ff00)
/// ```
///
/// Note the low byte is unused — `LIB_VERSION(4, 0, 1)` is `0x04000100`, not
/// `0x00040001`. Open-coding this shift at each call site is how one of them ends up
/// with the natural-looking packing and compares two numbers that are never equal.
pub const fn packed(version: (u32, u32, u32)) -> u32 {
    (version.0 << 24) | (version.1 << 16) | (version.2 << 8)
}
